### ISSUE TITLE
Inequality bug in optimizer

### ISSUE THREAD

**Issue by jeffpiep** [dmsc/tbxl-parser#1]
When optimization is turned on, there's a bug processing inequalities when a sum or difference is on the left-hand side of the sign. Example:

$options +optimize
? (a+b)<c
? c>(a+b)

produces:
0?A+B<C:?A+B>C

The second print statement has the inequality flipped. It should be ?A+B<C like the first.

**Comment by dmsc** [comment]
Release https://github.com/dmsc/tbxl-parser/releases/tag/v9.4.1 fixes this bug.

**Comment by jeffpiep** [comment]
This fixed it. Thank-you.
