### ISSUE TITLE
proc names

### ISSUE THREAD

**Issue by Sasatari** [dmsc/tbxl-parser#2]
Hello,
is there a way to keep the proc names? Currently they are converted to a, b, c...

**Comment by dmsc** [comment]
Hi,

You can use the "-f" option to keep all your variable names, currently there is no option to keep only names for PROCs. Remember that in TBXL, PROCs and variables use the same list of names.

**Comment by Sasatari** [comment]
Great, got it, works smooth. Using it with Irgendwer´s TURBAN. :)
